CREATE SCHEMA IF NOT EXISTS project DEFAULT CHARACTER SET utf8 ;
USE project ;

-- -----------------------------------------------------
-- Table USER
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS USER (
  idUSER INT NOT NULL,
  pnomeUSER VARCHAR(15) NOT NULL,
  lnomeUSER VARCHAR(15) NOT NULL,
  cpfUSER VARCHAR(15) NOT NULL,
  telUSER VARCHAR(15) NULL,
  celUSER VARCHAR(15) NULL,
  emailUSER VARCHAR(50) NOT NULL,
  funcaoUSER VARCHAR(10) NOT NULL,
  panelUSER VARCHAR(10) NOT NULL,
  usuarioUSER VARCHAR(20) NOT NULL,
  senhaUSER VARCHAR(16) NOT NULL,
  ativoUSER INT NOT NULL,
  PRIMARY KEY (idUSER))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table LOG
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS LOG (
  idLOG INT NOT NULL,
  dthoraLOG DATETIME NOT NULL,
  acaoLOG VARCHAR(25) NOT NULL,
  USER_idUSER INT NOT NULL,
  PRIMARY KEY (idLOG),
  INDEX fk_LOG_USER_idx (USER_idUSER ASC),
  CONSTRAINT fk_LOG_USER
    FOREIGN KEY (USER_idUSER)
    REFERENCES USER (idUSER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CAIXA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CAIXA (
  idCAIXA INT NOT NULL,
  dthoraCaixa DATETIME NOT NULL,
  trocoCAIXA DECIMAL(4,2) NOT NULL,
  vlrfinalCAIXA DECIMAL(5,2) NOT NULL,
  USER_idUSER INT NOT NULL,
  PRIMARY KEY (idCAIXA),
  INDEX fk_CAIXA_USER1_idx (USER_idUSER ASC),
  CONSTRAINT fk_CAIXA_USER1
    FOREIGN KEY (USER_idUSER)
    REFERENCES USER (idUSER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ENDERECO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ENDERECO (
  idENDERECO INT NOT NULL,
  ruaENDERECO VARCHAR(45) NOT NULL,
  numENDERECO INT NOT NULL,
  bairroENDERECO VARCHAR(45) NOT NULL,
  cityENDERECO VARCHAR(45) NOT NULL,
  ufENDERECO VARCHAR(2) NOT NULL,
  cepENDERECO VARCHAR(12) NOT NULL,
  PRIMARY KEY (idENDERECO))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CLIENTE (
  idCLIENTE INT NOT NULL,
  fnomeCLIENTE VARCHAR(20) NOT NULL,
  lnomeCLIENTE VARCHAR(20) NOT NULL,
  cpfCLIENTE VARCHAR(15) NOT NULL,
  telCLIENTE VARCHAR(15) NULL,
  celCLIENTE VARCHAR(15) NULL,
  ativaCLIENTE INT NOT NULL,
  ENDERECO_idENDERECO INT NOT NULL,
  PRIMARY KEY (idCLIENTE),
  INDEX fk_CLIENTE_ENDERECO1_idx (ENDERECO_idENDERECO ASC),
  CONSTRAINT fk_CLIENTE_ENDERECO1
    FOREIGN KEY (ENDERECO_idENDERECO)
    REFERENCES ENDERECO (idENDERECO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table MOVIMENTACAO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS MOVIMENTACAO (
  idMOVIMENTACAO INT NOT NULL,
  valorMOVIMENTACAO DECIMAL(5,2) NOT NULL,
  CAIXA_idCAIXA INT NOT NULL,
  USER_idUSER INT NOT NULL,
  CLIENTE_idCLIENTE INT NOT NULL,
  PRIMARY KEY (idMOVIMENTACAO),
  INDEX fk_MOVIMENTACAO_CAIXA1_idx (CAIXA_idCAIXA ASC),
  INDEX fk_MOVIMENTACAO_USER1_idx (USER_idUSER ASC),
  INDEX fk_MOVIMENTACAO_CLIENTE1_idx (CLIENTE_idCLIENTE ASC),
  CONSTRAINT fk_MOVIMENTACAO_CAIXA1
    FOREIGN KEY (CAIXA_idCAIXA)
    REFERENCES CAIXA (idCAIXA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_MOVIMENTACAO_USER1
    FOREIGN KEY (USER_idUSER)
    REFERENCES USER (idUSER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_MOVIMENTACAO_CLIENTE1
    FOREIGN KEY (CLIENTE_idCLIENTE)
    REFERENCES CLIENTE (idCLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table TIPO_PAG
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TIPO_PAG (
  idTIPO_PAG INT NOT NULL,
  nomeTIPO_PAG VARCHAR(20) NOT NULL,
  PRIMARY KEY (idTIPO_PAG))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table PAGAMENTO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PAGAMENTO (
  idPAGAMENYO INT NOT NULL,
  valorPAGMAENTO DECIMAL(5,2) NOT NULL,
  MOVIMENTACAO_idMOVIMENTACAO INT NOT NULL,
  TIPO_PAG_idTIPO_PAG INT NOT NULL,
  PRIMARY KEY (idPAGAMENYO),
  INDEX fk_PAGAMENYO_MOVIMENTACAO1_idx (MOVIMENTACAO_idMOVIMENTACAO ASC),
  INDEX fk_PAGAMENTO_TIPO_PAG1_idx (TIPO_PAG_idTIPO_PAG ASC),
  CONSTRAINT fk_PAGAMENYO_MOVIMENTACAO1
    FOREIGN KEY (MOVIMENTACAO_idMOVIMENTACAO)
    REFERENCES MOVIMENTACAO (idMOVIMENTACAO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PAGAMENTO_TIPO_PAG1
    FOREIGN KEY (TIPO_PAG_idTIPO_PAG)
    REFERENCES TIPO_PAG (idTIPO_PAG)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table EMPRESA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS EMPRESA (
  idEMPRESA INT NOT NULL,
  cnpjEMPRESA VARCHAR(20) NOT NULL,
  razsocEMPRESA VARCHAR(50) NOT NULL,
  nomfantEMPRESA VARCHAR(30) NOT NULL,
  ieEMPRESA VARCHAR(15) NOT NULL,
  telEMPRESA VARCHAR(15) NOT NULL,
  emailEMPRESA VARCHAR(50) NOT NULL,
  logoEMPRESA VARCHAR(45) NOT NULL,
  ativoEMPRESA INT NOT NULL,
  ENDERECO_idENDERECO INT NOT NULL,
  PRIMARY KEY (idEMPRESA),
  INDEX fk_EMPRESA_ENDERECO1_idx (ENDERECO_idENDERECO ASC),
  CONSTRAINT fk_EMPRESA_ENDERECO1
    FOREIGN KEY (ENDERECO_idENDERECO)
    REFERENCES ENDERECO (idENDERECO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table PRODUTO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PRODUTO (
  idPRODUTO INT NOT NULL,
  nomePRODUTO VARCHAR(15) NOT NULL,
  descPRODUTO VARCHAR(45) NOT NULL,
  custoPRODUTO DECIMAL(3,2) NOT NULL,
  vendaPRODUTO DECIMAL(3,2) NOT NULL,
  estkPRODUTO INT NULL,
  estkminPRODUTO INT NOT NULL,
  ativoPRODUTO INT NOT NULL,
  EMPRESA_idEMPRESA INT NOT NULL,
  PRIMARY KEY (idPRODUTO),
  INDEX fk_PRODUTO_EMPRESA1_idx (EMPRESA_idEMPRESA ASC),
  CONSTRAINT fk_PRODUTO_EMPRESA1
    FOREIGN KEY (EMPRESA_idEMPRESA)
    REFERENCES EMPRESA (idEMPRESA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table COMANDA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS COMANDA (
  idCOMANDA INT NOT NULL,
  qtdCOMANDA INT NOT NULL,
  valorCOMANDA DECIMAL(3,4) NOT NULL,
  MOVIMENTACAO_idMOVIMENTACAO INT NOT NULL,
  PRODUTO_idPRODUTO INT NOT NULL,
  PRIMARY KEY (idCOMANDA),
  INDEX fk_COMANDA_MOVIMENTACAO1_idx (MOVIMENTACAO_idMOVIMENTACAO ASC),
  INDEX fk_COMANDA_PRODUTO1_idx (PRODUTO_idPRODUTO ASC),
  CONSTRAINT fk_COMANDA_MOVIMENTACAO1
    FOREIGN KEY (MOVIMENTACAO_idMOVIMENTACAO)
    REFERENCES MOVIMENTACAO (idMOVIMENTACAO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_COMANDA_PRODUTO1
    FOREIGN KEY (PRODUTO_idPRODUTO)
    REFERENCES PRODUTO (idPRODUTO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ORDEM_SERVICO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ORDEM_SERVICO (
  idORDEM_SERVICO INT NOT NULL,
  statusORDEM_SERVICO VARCHAR(15) NOT NULL,
  dtfimORDEM_SERVICO DATE NOT NULL,
  garantORDEM_SERVICO VARCHAR(15) NOT NULL,
  descORDEM_SERVICO VARCHAR(100) NOT NULL,
  deftORDEM_SERVICO VARCHAR(100) NOT NULL,
  obsORDEM_SERVICO VARCHAR(100) NOT NULL,
  protcORDEM_SERVICO VARCHAR(15) NOT NULL,
  dtemissaoORDEM_SERVICO DATE NOT NULL,
  USER_idUSER INT NOT NULL,
  CLIENTE_idCLIENTE INT NOT NULL,
  PRIMARY KEY (idORDEM_SERVICO),
  INDEX fk_ORDEM_SERVICO_USER1_idx (USER_idUSER ASC),
  INDEX fk_ORDEM_SERVICO_CLIENTE1_idx (CLIENTE_idCLIENTE ASC),
  CONSTRAINT fk_ORDEM_SERVICO_USER1
    FOREIGN KEY (USER_idUSER)
    REFERENCES USER (idUSER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ORDEM_SERVICO_CLIENTE1
    FOREIGN KEY (CLIENTE_idCLIENTE)
    REFERENCES CLIENTE (idCLIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table RECEBER
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS RECEBER (
  idRECEBER INT NOT NULL,
  valorRECEBER DECIMAL(3,2) NOT NULL,
  MOVIMENTACAO_idMOVIMENTACAO INT NOT NULL,
  ORDEM_SERVICO_idORDEM_SERVICO INT NOT NULL,
  PRIMARY KEY (idRECEBER),
  INDEX fk_RECEBER_MOVIMENTACAO1_idx (MOVIMENTACAO_idMOVIMENTACAO ASC),
  INDEX fk_RECEBER_ORDEM_SERVICO1_idx (ORDEM_SERVICO_idORDEM_SERVICO ASC),
  CONSTRAINT fk_RECEBER_MOVIMENTACAO1
    FOREIGN KEY (MOVIMENTACAO_idMOVIMENTACAO)
    REFERENCES MOVIMENTACAO (idMOVIMENTACAO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_RECEBER_ORDEM_SERVICO1
    FOREIGN KEY (ORDEM_SERVICO_idORDEM_SERVICO)
    REFERENCES ORDEM_SERVICO (idORDEM_SERVICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table SERVICO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS SERVICO (
  idSERVICO INT NOT NULL,
  nomeSERVICO VARCHAR(35) NOT NULL,
  valorSERVICO DECIMAL(3,2) NOT NULL,
  ativoSERVICO INT NOT NULL,
  USER_idUSER INT NOT NULL,
  PRIMARY KEY (idSERVICO),
  INDEX fk_SERVICO_USER1_idx (USER_idUSER ASC),
  CONSTRAINT fk_SERVICO_USER1
    FOREIGN KEY (USER_idUSER)
    REFERENCES USER (idUSER)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table OS_SERV
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS OS_SERV (
  idOS_SERV INT NOT NULL,
  SERVICO_idSERVICO INT NOT NULL,
  ORDEM_SERVICO_idORDEM_SERVICO INT NOT NULL,
  PRIMARY KEY (idOS_SERV),
  INDEX fk_OS_SERV_SERVICO1_idx (SERVICO_idSERVICO ASC),
  INDEX fk_OS_SERV_ORDEM_SERVICO1_idx (ORDEM_SERVICO_idORDEM_SERVICO ASC),
  CONSTRAINT fk_OS_SERV_SERVICO1
    FOREIGN KEY (SERVICO_idSERVICO)
    REFERENCES SERVICO (idSERVICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_OS_SERV_ORDEM_SERVICO1
    FOREIGN KEY (ORDEM_SERVICO_idORDEM_SERVICO)
    REFERENCES ORDEM_SERVICO (idORDEM_SERVICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table PROD_SERV
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PROD_SERV (
  idPROD_SERV INT NOT NULL,
  qtdPROD_SERV INT NOT NULL,
  PRODUTO_idPRODUTO INT NOT NULL,
  SERVICO_idSERVICO INT NOT NULL,
  PRIMARY KEY (idPROD_SERV, PRODUTO_idPRODUTO),
  INDEX fk_PROD_SERV_PRODUTO1_idx (PRODUTO_idPRODUTO ASC),
  INDEX fk_PROD_SERV_SERVICO1_idx (SERVICO_idSERVICO ASC),
  CONSTRAINT fk_PROD_SERV_PRODUTO1
    FOREIGN KEY (PRODUTO_idPRODUTO)
    REFERENCES PRODUTO (idPRODUTO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PROD_SERV_SERVICO1
    FOREIGN KEY (SERVICO_idSERVICO)
    REFERENCES SERVICO (idSERVICO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- ----------------------------------------------------
-- Insert Table USER
-- ----------------------------------------------------
INSERT INTO project.USER VALUES ()